"""``system-addon-user-defined-states`` wrapper.

Unlike timed-events and scene-responders, this addon's tree is **not** a
flat ``entries/`` list - it has four sub-categories under
``/scripts/system-addon-user-defined-states/``:

- ``device-sensor-states`` - states bound to physical sensor values
- ``custom-states`` - user-toggleable switches (set/reset labels)
- ``combined-states`` - logical combinations (AND/OR) of other states
- ``triggered-states`` - event-driven states with set+reset triggers

Save protocol verified via DevTools capture 2026-05-30:

- Event-Name: ``system-addon-user-defined-states.config`` (DOT)
- Reply-Event: ``system-addon-user-defined-states.saved`` (DOT)
- **Universal payload** with a ``type`` discriminator field (matches the
  category). All other category-specific containers must be present but
  may be empty/null defaults.
"""

from __future__ import annotations

import logging
from typing import Any, Mapping

from ..exceptions import DssNotFoundError, DssProtocolError
from ..models import (
    CombinedCondition,
    UserState,
    UserStateCategory,
    UserStateValue,
    ZoneSensorStateConfig,
)
from .base import AddonBase

_LOGGER = logging.getLogger(__name__)


class UserStatesAddon(AddonBase):
    """Wrapper around ``/scripts/system-addon-user-defined-states/<category>/<id>``."""

    addon_name = "system-addon-user-defined-states"

    CATEGORIES: tuple[UserStateCategory, ...] = (
        UserStateCategory.DEVICE_SENSOR,
        UserStateCategory.CUSTOM,
        UserStateCategory.COMBINED,
        UserStateCategory.TRIGGERED,
    )

    async def list_states(
        self,
        category: UserStateCategory | None = None,
    ) -> list[UserState]:
        """List all states, optionally filtered by category."""
        categories = (category,) if category is not None else self.CATEGORIES
        out: list[UserState] = []
        for cat in categories:
            ids = await self._list_ids_in_category(cat)
            for state_id in ids:
                try:
                    state = await self._load_state(cat, state_id)
                except Exception as exc:  # noqa: BLE001
                    _LOGGER.debug(
                        "[pydss.addons.user_states] %s/%s load failed: %s",
                        cat.value, state_id, exc,
                    )
                    continue
                if state is not None:
                    out.append(state)
        return out

    async def get_state(self, state_id: str, category: UserStateCategory | None = None) -> UserState | None:
        """Look up one state by id; if category unknown, scan all."""
        categories = (category,) if category is not None else self.CATEGORIES
        for cat in categories:
            state = await self._load_state(cat, state_id)
            if state is not None:
                return state
        return None

    async def set_state_value(self, state_name: str, value: str | int) -> None:
        """Set a user-state's current value.

        Uses the global ``/json/state/set`` endpoint - the state name is the
        addressable identifier in the state namespace (not the numeric
        state-id under ``user-defined-states/``). Look up the name via
        :meth:`get_state` first.
        """
        await self._client.get(
            "/json/state/set",
            params={"name": state_name, "value": str(value)},
        )
        _LOGGER.info("[pydss.addons.user_states] set state %s = %s", state_name, value)

    async def get_state_value(self, state_name: str) -> str | None:
        """Read a user-state's current value via ``/json/state/get``."""
        result = await self._client.get(
            "/json/state/get",
            params={"name": state_name},
        )
        if isinstance(result, Mapping):
            value = result.get("value")
            if value is not None:
                return str(value)
        return None

    async def save_state(
        self,
        state: UserState,
        *,
        wait_for_reply: bool = True,
        reply_timeout_s: float = 5.0,
    ) -> str | None:
        """Create or update a user-defined state.

        On create, set ``state.state_id`` to an empty string - the dSS
        assigns a Unix-timestamp-style id automatically.

        Supported categories (verified via DevTools capture 2026-05-30):

        - :attr:`UserStateCategory.CUSTOM` - fully supported (CRUD)
        - :attr:`UserStateCategory.COMBINED` - structure ready, save
          format extrapolated from custom-states pattern (not yet
          live-verified - try and report)
        - :attr:`UserStateCategory.TRIGGERED` - structure ready, save
          format extrapolated (not yet live-verified)
        - :attr:`UserStateCategory.DEVICE_SENSOR` - read-only typically,
          generated by other addons

        Returns:
            The state id on success, or None on reply timeout.
        """
        payload = serialize_user_state_for_save(state)
        reply = await self.raise_config(
            action="save",
            value=payload,
            wait_for_reply=wait_for_reply,
            reply_timeout_s=reply_timeout_s,
        )
        if not wait_for_reply:
            return None
        if reply is None:
            _LOGGER.warning("[pydss.addons.user_states] save: no reply within timeout")
            return None
        if reply.get("complete") != "success":
            _LOGGER.warning("[pydss.addons.user_states] save reply: %s", dict(reply))

        # The saved-event payload includes the (newly assigned) id directly -
        # no list-scan needed. Falls back to name-lookup if the reply is
        # missing the id for some reason.
        if "id" in reply:
            return str(reply["id"])
        if not state.state_id:
            after = await self.list_states(state.category)
            for s in after:
                if s.name == state.name:
                    return s.state_id
            return None
        return state.state_id

    async def delete_state(
        self,
        state_id: str,
        category: UserStateCategory | None = None,
    ) -> None:
        """Delete a user-defined state by id via property-tree removal.

        If ``category`` is None, scans all categories to find the state.
        Pass the category explicitly when known to save one round-trip.
        """
        if category is None:
            state = await self.get_state(state_id)
            if state is None:
                raise DssNotFoundError(
                    f"[pydss.addons.user_states] no state {state_id!r}"
                )
            category = state.category

        path = f"/scripts/system-addon-user-defined-states/{category.value}/{state_id}"
        try:
            await self._client.get("/json/property/remove", params={"path": path})
            _LOGGER.info("[pydss.addons.user_states] removed %s", path)
        except DssProtocolError as exc:
            msg = str(exc).lower()
            if "could not find" in msg or "not found" in msg:
                raise DssNotFoundError(
                    f"[pydss.addons.user_states] no state {state_id!r} in {category.value}"
                ) from exc
            raise

    async def _list_ids_in_category(self, category: UserStateCategory) -> list[str]:
        path = f"{self.base_path}/{category.value}"
        try:
            children = await self._walker.get_children(path)
        except Exception as exc:  # noqa: BLE001
            _LOGGER.debug("[pydss.addons.user_states] %s missing: %s", path, exc)
            return []
        return [c.name for c in children if c.is_leaf is False]

    async def _load_state(
        self,
        category: UserStateCategory,
        state_id: str,
    ) -> UserState | None:
        path = f"{self.base_path}/{category.value}/{state_id}"
        try:
            raw = await self._walker.walk(path)
        except Exception:  # noqa: BLE001
            return None
        if not raw:
            return None
        return parse_user_state(state_id, category, raw)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def parse_user_state(
    state_id: str,
    category: UserStateCategory,
    raw: Mapping[str, Any],
) -> UserState:
    """Convert the raw sub-tree dict into a :class:`UserState`."""
    set_triggers, set_lag = _parse_triggered_set(raw, "setTrigger")
    reset_triggers, reset_lag = _parse_triggered_set(raw, "resetTrigger")
    return UserState(
        state_id=str(raw.get("id", state_id)),
        name=str(raw.get("name", state_id)),
        category=category,
        current_value=_extract_current_value(raw),
        values=_parse_values(raw.get("values")),
        set_name=_str_or_none(raw.get("setName")),
        reset_name=_str_or_none(raw.get("resetName")),
        show_on_phone=_bool_or_none(raw.get("showOnPhone")),
        combined_and=_parse_combined_and(raw),
        set_triggers=set_triggers,
        reset_triggers=reset_triggers,
        set_retriggering_lag=set_lag,
        reset_retriggering_lag=reset_lag,
        zone_sensor=_parse_zone_sensor(raw),
    )


def _parse_zone_sensor(raw: Mapping[str, Any]) -> ZoneSensorStateConfig | None:
    sensor_state = raw.get("sensorState")
    if not isinstance(sensor_state, Mapping):
        return None
    zone = sensor_state.get("zone")
    if not isinstance(zone, Mapping):
        return None
    try:
        return ZoneSensorStateConfig(
            zone_id=int(zone.get("zoneID", 0)),
            group_id=int(zone.get("groupID", 0)),
            type_id=int(zone.get("typeID", 0)),
            active_value=float(zone.get("activeValue", 0)),
            inactive_value=float(zone.get("inactiveValue", 0)),
            greater_on_set=bool(zone.get("greaterOnSet", True)),
        )
    except (ValueError, TypeError):
        return None


def _parse_triggered_set(
    raw: Mapping[str, Any],
    key: str,
) -> tuple[tuple[Any, ...], int]:
    """Parse a setTrigger / resetTrigger sub-object.

    Read-back shape (property tree)::

        "setTrigger": {
            "triggers": {"1": {"type": "zone-scene", ...}},
            "actions": {"0": {...}}
        }

    Save shape (DevTools-captured)::

        "setTrigger": [{"type": "zone-scene", ...}]

    Returns a tuple of (parsed ResponderTriggers, lag-seconds). Both shapes
    are tolerated - we look in ``activityState[key]`` first (save shape),
    then fall back to ``[key]`` (read shape).
    """
    from ..models import ResponderTrigger
    activity = raw.get("activityState")
    container = activity.get(key) if isinstance(activity, Mapping) else None
    if container is None:
        container = raw.get(key)

    triggers_out: list[Any] = []
    if isinstance(container, list):
        for item in container:
            if isinstance(item, Mapping):
                triggers_out.append(ResponderTrigger.from_raw(item))
    elif isinstance(container, Mapping):
        # Read shape: {"triggers": {"1": {...}}} or flat indexed dict
        inner = container.get("triggers")
        if isinstance(inner, Mapping):
            for k in sorted(inner.keys(), key=_int_key_safe):
                v = inner[k]
                if isinstance(v, Mapping):
                    triggers_out.append(ResponderTrigger.from_raw(v))
        else:
            for k in sorted(container.keys(), key=_int_key_safe):
                v = container[k]
                if isinstance(v, Mapping) and "type" in v:
                    triggers_out.append(ResponderTrigger.from_raw(v))

    # Retriggering lag - look in activityState (save shape)
    lag = 0
    if isinstance(activity, Mapping):
        lag_key = "setRetriggeringLag" if key == "setTrigger" else "resetRetriggeringLag"
        try:
            lag = int(activity.get(lag_key, 0))
        except (ValueError, TypeError):
            lag = 0
    return tuple(triggers_out), lag


def _int_key_safe(s: Any) -> int:
    try:
        return int(s)
    except (ValueError, TypeError):
        return 0


def _parse_combined_and(raw: Mapping[str, Any]) -> tuple[CombinedCondition, ...]:
    """Extract combined-state AND conditions.

    Looks at ``combinedState.and`` (save payload shape) first, then
    ``combined.and`` (legacy / property-tree-read shape). Each condition
    has ``state``, ``value`` plus either ``addonid`` (combined-states
    save) or ``addon-id`` (legacy/read shape).
    """
    for container_key in ("combinedState", "combined"):
        container = raw.get(container_key)
        if not isinstance(container, Mapping):
            continue
        and_list = container.get("and")
        if not isinstance(and_list, list):
            continue
        out: list[CombinedCondition] = []
        for item in and_list:
            if not isinstance(item, Mapping):
                continue
            addon_id = item.get("addonid") or item.get("addon-id") or ""
            out.append(CombinedCondition(
                state=str(item.get("state", "")),
                value=str(item.get("value", "")),
                addon_id=str(addon_id),
            ))
        return tuple(out)
    return ()


def _str_or_none(v: Any) -> str | None:
    if v is None or v == "":
        return None
    return str(v)


def _bool_or_none(v: Any) -> bool | None:
    if v is None:
        return None
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return bool(v)
    if isinstance(v, str):
        s = v.strip().lower()
        if s in ("true", "1", "yes"):
            return True
        if s in ("false", "0", "no"):
            return False
    return None


# ---------------------------------------------------------------------------
# Serialization (save) - universal payload with type discriminator
# ---------------------------------------------------------------------------


def serialize_user_state_for_save(state: UserState) -> dict[str, Any]:
    """Build the save-payload in the format the dSS web UI uses.

    Verified via DevTools capture 2026-05-30 (custom-state create). The dSS
    expects a unified payload with a ``type`` discriminator field (matching
    the category) - all other category-specific containers must be present
    too, mostly as null/empty defaults.

    Captured custom-state save body (decoded)::

        {
          "name": "test", "showOnPhone": null, "type": "custom-states",
          "setName": "1", "resetName": "2", "id": null,
          "activityState": {},
          "combinedState": {"and": []},
          "sensorState": {},
          "consumptionState": {
            "dSID": null, "setRetriggeringLag": 0, "resetRetriggeringLag": 0
          },
          "powerState": null,
          "productionP1State": null,
          "consumptionP1State": null,
          "productionModbusState": null,
          "consumptionModbusState": null,
          "apartmentPowerState": null,
          "windowState": []
        }

    For combined-states and triggered-states the relevant container fields
    (combinedState / activityState) are populated from the typed model
    fields; the payload still includes all the other null defaults.
    """
    payload: dict[str, Any] = {
        "name": state.name,
        "showOnPhone": state.show_on_phone,
        "type": state.category.value,
        "setName": state.set_name,
        "resetName": state.reset_name,
        "id": state.state_id or None,
        # Universal container defaults - the dSS REQUIRES these to be present
        "activityState": {},
        "combinedState": {"and": []},
        "sensorState": {},
        "consumptionState": {
            "dSID": None,
            "setRetriggeringLag": 0,
            "resetRetriggeringLag": 0,
        },
        "powerState": None,
        "productionP1State": None,
        "consumptionP1State": None,
        "productionModbusState": None,
        "consumptionModbusState": None,
        "apartmentPowerState": None,
        "windowState": [],
    }

    # Category-specific overrides
    if state.category is UserStateCategory.COMBINED:
        # combinedState.and = [{state, value, addonid}, ...]
        # Note: dSS uses ``addonid`` (no hyphen) in this specific container,
        # inconsistent with ``addon-id`` elsewhere - verified via DevTools
        # capture 2026-05-30.
        payload["combinedState"] = {
            "and": [
                {"state": c.state, "value": c.value, "addonid": c.addon_id}
                for c in state.combined_and
            ],
        }
    if state.category is UserStateCategory.ZONE_SENSOR and state.zone_sensor is not None:
        # Verified via DevTools capture 2026-05-30. sensorState.zone holds
        # the threshold config. Hysteresis: active_value vs inactive_value
        # may differ; same value means sharp threshold.
        payload["sensorState"] = {
            "zone": {
                "greaterOnSet": state.zone_sensor.greater_on_set,
                "activeValue": state.zone_sensor.active_value,
                "zoneID": state.zone_sensor.zone_id,
                "groupID": state.zone_sensor.group_id,
                "typeID": state.zone_sensor.type_id,
                "inactiveValue": state.zone_sensor.inactive_value,
            },
        }
    if state.category is UserStateCategory.TRIGGERED:
        # Verified via DevTools capture 2026-05-30. activityState has:
        #   - setTrigger:  flat array of trigger objects (NOT indexed dict)
        #   - resetTrigger: same
        #   - setRetriggeringLag / resetRetriggeringLag: int seconds
        # The "actions" subtree (change-addon-state on self) is auto-generated
        # by the dSS on save - we don't send it.
        payload["activityState"] = {
            "setTrigger": [_serialize_state_trigger(t) for t in state.set_triggers],
            "resetTrigger": [_serialize_state_trigger(t) for t in state.reset_triggers],
            "setRetriggeringLag": state.set_retriggering_lag,
            "resetRetriggeringLag": state.reset_retriggering_lag,
        }

    return payload


def _serialize_state_trigger(trigger: Any) -> dict[str, Any]:
    """Flatten a :class:`ResponderTrigger` into the triggered-state save format.

    Only emits fields that are set on the trigger - matches the captured
    ``{"type": "zone-scene", "zone": 9, "group": 2, "scene": 17}`` shape.
    """
    out: dict[str, Any] = {"type": trigger.trigger_type.value}
    optional_map = {
        "addon-id": trigger.addon_id,
        "name": trigger.name,
        "state": trigger.state,
        "dsuid": trigger.dsuid,
        "msg": trigger.msg,
        "buttonIndex": trigger.button_index,
        "zone": trigger.zone,
        "group": trigger.group,
        "scene": trigger.scene,
        "event": trigger.event,
    }
    for k, v in optional_map.items():
        if v is not None:
            out[k] = v
    return out


def _extract_current_value(raw: Mapping[str, Any]) -> int | str | None:
    """Try a few field names where the dSS stashes the current value."""
    for key in ("value", "current", "state"):
        v = raw.get(key)
        if v is not None:
            return v if isinstance(v, (str, int)) else str(v)
    return None


def _parse_values(raw: Any) -> tuple[UserStateValue, ...]:
    """Optional enum-of-values, e.g. ``{"0":{"value":0,"label":"off"},"1":...}``."""
    if not isinstance(raw, Mapping):
        return ()
    out: list[UserStateValue] = []
    for key in sorted(raw.keys(), key=_int_key):
        v = raw[key]
        if isinstance(v, Mapping):
            try:
                out.append(UserStateValue(
                    value=int(v.get("value", key)),
                    label=str(v.get("label", "")),
                ))
            except (ValueError, TypeError):
                continue
    return tuple(out)


def _int_key(s: str) -> int:
    try:
        return int(s)
    except (ValueError, TypeError):
        return 0
