"""pydigitalstrom - async Python library for the digitalSTROM dSS REST API.

HA-agnostic. Targets the Bridge-Phase of the ioBroker -> Home Assistant -> KNX
migration (see ``docs/LIBRARY_DESIGN.md`` section 11 for the strategic context).
"""

from __future__ import annotations

from .addons import (
    AddonBase,
    SceneResponderAddon,
    TimedEventsAddon,
    UserActionsAddon,
    UserStatesAddon,
    parse_scene_responder,
    parse_timed_event,
    parse_user_action,
    parse_user_state,
    serialize_scene_responder_for_save,
    serialize_timed_event,
    serialize_user_action,
    serialize_user_action_for_save,
    serialize_user_state_for_save,
)
from .alarms import (
    AlarmContext,
    AlarmEngine,
    AlarmEvent,
    AlarmRule,
    CircuitOutageRule,
    MotionWhileAbsentRule,
    SensorOutageRule,
    Severity,
    UserStateAlarmRule,
    ZoneTemperatureLowRule,
)
from .apartment import (
    fetch_apartment,
    fetch_apartment_circuits,
    fetch_apartment_name,
    parse_apartment_structure,
    parse_circuits,
)
from .auth import AppToken, SessionManager
from .circuits import (
    CircuitMonitor,
    CircuitReading,
    CircuitState,
    classify_state,
    short_dsid_from_dsuid,
)
from .client import DssClient
from .events import (
    EVENT_NAMES,
    ButtonClickEvent,
    CallSceneEvent,
    DeviceBinaryInputEvent,
    DeviceEvent,
    DeviceSensorEvent,
    DssEvent,
    EventDispatcher,
    EventStream,
    ExecutionDeniedEvent,
    HighLevelEvent,
    ModelReadyEvent,
    RunningEvent,
    StateChangeEvent,
    UndoSceneEvent,
    ZoneSensorErrorEvent,
    ZoneSensorValueEvent,
    parse_event,
)
from .exceptions import (
    DssAuthError,
    DssConnectionError,
    DssError,
    DssNotFoundError,
    DssProtocolError,
    DssSubscriptionError,
    DssTimeoutError,
    DssTypeMismatchError,
)
from .models import (
    GROUP_BROADCAST,
    GROUP_LIGHT,
    GROUP_SHADE,
    SYSTEM_ZONE_IDS,
    Apartment,
    BinaryInput,
    Circuit,
    ClickType,
    Cluster,
    CombinedCondition,
    Device,
    DeviceCapabilities,
    EventSource,
    Group,
    OutputChannel,
    OutputMode,
    ResponderTrigger,
    ResponderTriggerType,
    SceneCall,
    SceneResponder,
    Sensor,
    SensorType,
    StandardScene,
    TimeBase,
    TimedEvent,
    TimedEventRecurrence,
    TimedEventTime,
    UserAction,
    UserActionAction,
    UserActionConditions,
    UserActionType,
    UserState,
    UserStateCategory,
    UserStateValue,
    Weekday,
    Zone,
    ZoneSensorStateConfig,
)
from .property import PropertyChild, PropertyTreeWalker, PropertyType

__version__ = "0.1.0"

__all__ = [
    "EVENT_NAMES",
    "GROUP_BROADCAST",
    "GROUP_LIGHT",
    "GROUP_SHADE",
    "SYSTEM_ZONE_IDS",
    # Addons
    "AddonBase",
    "AlarmContext",
    "AlarmEngine",
    "AlarmEvent",
    "AlarmRule",
    # Apartment
    "Apartment",
    # Client / auth
    "AppToken",
    "BinaryInput",
    "ButtonClickEvent",
    "CallSceneEvent",
    "Circuit",
    # Circuits + alarms
    "CircuitMonitor",
    "CircuitOutageRule",
    "CircuitReading",
    "CircuitState",
    "ClickType",
    "Cluster",
    "CombinedCondition",
    "Device",
    "DeviceBinaryInputEvent",
    "DeviceCapabilities",
    "DeviceEvent",
    "DeviceSensorEvent",
    "DssAuthError",
    "DssClient",
    "DssConnectionError",
    # Exceptions
    "DssError",
    "DssEvent",
    "DssNotFoundError",
    "DssProtocolError",
    "DssSubscriptionError",
    "DssTimeoutError",
    "DssTypeMismatchError",
    "EventDispatcher",
    # Events
    "EventSource",
    "EventStream",
    "ExecutionDeniedEvent",
    "Group",
    "HighLevelEvent",
    "ModelReadyEvent",
    "MotionWhileAbsentRule",
    "OutputChannel",
    "OutputMode",
    "PropertyChild",
    # Property tree
    "PropertyTreeWalker",
    "PropertyType",
    "ResponderTrigger",
    "ResponderTriggerType",
    "RunningEvent",
    # Scenes
    "SceneCall",
    "SceneResponder",
    "SceneResponderAddon",
    "Sensor",
    "SensorOutageRule",
    "SensorType",
    "SessionManager",
    "Severity",
    "StandardScene",
    "StateChangeEvent",
    "TimeBase",
    "TimedEvent",
    "TimedEventRecurrence",
    "TimedEventTime",
    "TimedEventsAddon",
    "UndoSceneEvent",
    # Addon models (v0.2)
    "UserAction",
    "UserActionAction",
    "UserActionConditions",
    "UserActionType",
    "UserActionsAddon",
    "UserState",
    "UserStateAlarmRule",
    "UserStateCategory",
    "UserStateValue",
    "UserStatesAddon",
    "Weekday",
    "Zone",
    "ZoneSensorErrorEvent",
    "ZoneSensorStateConfig",
    "ZoneSensorValueEvent",
    "ZoneTemperatureLowRule",
    "__version__",
    "classify_state",
    "fetch_apartment",
    "fetch_apartment_circuits",
    "fetch_apartment_name",
    "parse_apartment_structure",
    "parse_circuits",
    "parse_event",
    "parse_scene_responder",
    "parse_timed_event",
    "parse_user_action",
    "parse_user_state",
    "serialize_scene_responder_for_save",
    "serialize_timed_event",
    "serialize_user_action",
    "serialize_user_action_for_save",
    "serialize_user_state_for_save",
    "short_dsid_from_dsuid",
]
