"""Circuit / dSM-Meter monitoring with outage detection.

The dSS exposes circuit power via two paths:

1. ``/json/circuit/getConsumption?id=<SHORT_DSID>`` and
   ``/json/circuit/getEnergyMeterValue?id=<SHORT_DSID>`` - simple but limited
2. Property tree ``/apartment/dSMeters/<DSUID>/`` - rich, with status flags

This module uses the property tree (one round-trip group per circuit) since
we need the status flags for outage detection anyway.

Outage detection follows the empirically verified pattern documented in
``docs/DSS_API_NOTES.md`` (section "Outage-Detection-Regeln").
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any

from .apartment import fetch_apartment_circuits
from .client import DssClient
from .exceptions import DssError
from .models import Circuit

_LOGGER = logging.getLogger(__name__)


class CircuitState(str, Enum):
    """Operational state of a dSM-Meter.

    See ``docs/DSS_API_NOTES.md`` for the verified pattern table.
    Higher-severity states take precedence when multiple flags match.
    """

    NORMAL = "normal"
    """``state=0, present=True, isValid=True`` - everything fine."""

    POWERING_UP = "powering_up"
    """``state=1`` (with present=True) - dSM was recently re-energized.

    Lasts ~4 minutes after a fresh power-up. NOT an alarm condition; a
    legitimate signal that a circuit just came back online.
    """

    OFFLINE = "offline"
    """``present=False, state=0`` - circuit just lost power (breaker tripped)."""

    UNREACHABLE = "unreachable"
    """``state=255`` - circuit has been offline long enough that the dSS
    marks it permanently dead (Tom's F6 pattern, days unpowered)."""

    VIRTUAL = "virtual"
    """No real dSM - virtual circuit like the Hue-Bridge integration in dSS.
    ``circuit/getConsumption`` fails with a bus parse error."""

    UNKNOWN = "unknown"


@dataclass(frozen=True, slots=True)
class CircuitReading:
    """Single snapshot of a dSM-Meter's power + status.

    Generated by :meth:`CircuitMonitor.read_one` and :meth:`CircuitMonitor.read_all`.
    """

    dsuid: str
    dsid: str
    name: str
    state: CircuitState
    watts: int | None
    energy_wh: float | None
    power_last_seen: datetime | None
    """When the dSM last updated its powerConsumption (None if missing)."""
    energy_last_seen: datetime | None
    """When the dSM last updated its energyMeterValue (None if missing)."""
    raw_state: int | None
    raw_is_valid: bool | None
    raw_present: bool | None
    raw_authorized: bool | None
    raw_is_initialized: bool | None
    timestamp: datetime

    @property
    def power_age_seconds(self) -> float | None:
        """Seconds since the dSM last refreshed powerConsumption."""
        if self.power_last_seen is None:
            return None
        return (self.timestamp - self.power_last_seen).total_seconds()

    @property
    def energy_age_seconds(self) -> float | None:
        """Seconds since the dSM last refreshed energyMeterValue."""
        if self.energy_last_seen is None:
            return None
        return (self.timestamp - self.energy_last_seen).total_seconds()

    @property
    def is_outage(self) -> bool:
        """True if the circuit is currently offline (any outage flavour)."""
        return self.state in (CircuitState.OFFLINE, CircuitState.UNREACHABLE)

    @property
    def is_recovering(self) -> bool:
        """True if the circuit was recently re-energized (POWERING_UP)."""
        return self.state is CircuitState.POWERING_UP

    @property
    def is_real_meter(self) -> bool:
        """True if the circuit is a physical dSM (not virtual like Hue)."""
        return self.state is not CircuitState.VIRTUAL


def short_dsid_from_dsuid(dsuid: str) -> str:
    """Derive the short 24-char dSID from a 33-char dSUID.

    Empirical mapping: ``dsid = dsuid[:11] + dsuid[20:33]`` (11 + 13 = 24 chars).
    Prefer using ``Circuit.dsid`` directly when available - the dSS returns
    the canonical short form in ``apartment/getCircuits`` so this helper is
    only a fallback.
    """
    if len(dsuid) >= 33:
        return dsuid[:11] + dsuid[20:33]
    return dsuid


def classify_state(
    *,
    raw_state: int | None,
    raw_present: bool | None,
    raw_is_valid: bool | None,
    consumption_api_failed: bool = False,
) -> CircuitState:
    """Apply the documented outage-detection rules to raw flags.

    Order of precedence (highest severity first):

    1. ``state == 255`` -> ``UNREACHABLE``
    2. ``present == False`` -> ``OFFLINE``
    3. ``raw_state == 1`` -> ``POWERING_UP``
    4. ``consumption_api_failed and present`` -> ``VIRTUAL``
    5. all flags consistent (state=0, present=True, valid=True) -> ``NORMAL``
    6. anything else -> ``UNKNOWN``
    """
    if raw_state == 255:
        return CircuitState.UNREACHABLE
    if raw_present is False:
        return CircuitState.OFFLINE
    if raw_state == 1:
        return CircuitState.POWERING_UP
    if consumption_api_failed and raw_present is True:
        return CircuitState.VIRTUAL
    if raw_state == 0 and raw_present is True and raw_is_valid is True:
        return CircuitState.NORMAL
    return CircuitState.UNKNOWN


# Properties we read from /apartment/dSMeters/<dsuid>/
# Mapping: (property name, getter, dest field, parser)
_READ_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("powerConsumption", "getInteger", "watts"),
    ("powerConsumptionAge", "getString", "power_age"),
    ("energyMeterValue", "getFloating", "energy_wh"),
    ("energyMeterAge", "getString", "energy_age"),
    ("state", "getInteger", "raw_state"),
    ("present", "getBoolean", "raw_present"),
    ("isValid", "getBoolean", "raw_is_valid"),
    ("authorized", "getBoolean", "raw_authorized"),
    ("isInitialized", "getBoolean", "raw_is_initialized"),
)


class CircuitMonitor:
    """Polls all circuits + classifies their state.

    Usage::

        monitor = CircuitMonitor(client, poll_interval_s=30)
        readings = await monitor.read_all()
        for r in readings:
            print(f"{r.name}: {r.watts}W  state={r.state.value}")

        # Or as a stream:
        async for reading in monitor.stream():
            ...
    """

    def __init__(
        self,
        client: DssClient,
        *,
        poll_interval_s: float = 30.0,
        circuit_refresh_s: float = 600.0,
    ) -> None:
        """Args:
            client: Authenticated DssClient.
            poll_interval_s: Time between full polls of every circuit.
            circuit_refresh_s: Time between re-fetching the circuit list
                from ``apartment/getCircuits`` (handles dSM-Adds/Removes).
        """
        self._client = client
        self._poll_interval = poll_interval_s
        self._circuit_refresh = circuit_refresh_s
        self._circuits: list[Circuit] = []
        self._last_circuits_refresh: float = 0.0
        self._last_readings: dict[str, CircuitReading] = {}

    @property
    def last_readings(self) -> dict[str, CircuitReading]:
        """Most recent reading per dSUID."""
        return dict(self._last_readings)

    async def _ensure_circuits(self) -> None:
        loop = asyncio.get_event_loop()
        now = loop.time()
        if not self._circuits or (now - self._last_circuits_refresh) > self._circuit_refresh:
            self._circuits = list(await fetch_apartment_circuits(self._client))
            self._last_circuits_refresh = now
            _LOGGER.debug("[pydss.circuits] Refreshed circuit list: %d entries", len(self._circuits))

    async def read_all(self) -> list[CircuitReading]:
        """Read every circuit's status sequentially.

        Each circuit triggers ~10 property reads internally, so reading 7
        circuits in parallel would fire ~70 concurrent requests and the dSS
        starts dropping responses. Sequential per-circuit reads (with the
        internal property reads still parallel within one circuit) hits a
        sweet spot of latency vs. reliability.
        """
        await self._ensure_circuits()
        out: list[CircuitReading] = []
        for c in self._circuits:
            try:
                r = await self._read_one_circuit(c)
            except DssError as exc:
                _LOGGER.warning("[pydss.circuits] read %s failed: %s", c.name, exc)
                continue
            out.append(r)
            self._last_readings[c.dsuid] = r
        return out

    async def read_one(self, dsuid: str) -> CircuitReading | None:
        """Read a single circuit by dSUID."""
        await self._ensure_circuits()
        for c in self._circuits:
            if c.dsuid == dsuid:
                try:
                    r = await self._read_one_circuit(c)
                except DssError as exc:
                    _LOGGER.warning("[pydss.circuits] read %s failed: %s", dsuid, exc)
                    return None
                self._last_readings[c.dsuid] = r
                return r
        return None

    async def stream(self) -> AsyncIterator[CircuitReading]:
        """Yield readings forever, one full sweep per poll_interval_s.

        Cancel via task.cancel() or break the loop.
        """
        while True:
            readings = await self.read_all()
            for r in readings:
                yield r
            await asyncio.sleep(self._poll_interval)

    async def stream_state_changes(self) -> AsyncIterator[tuple[CircuitReading, CircuitReading]]:
        """Yield only state-change events as (previous, current) pairs.

        First reading of every circuit is silent (no transition to report).
        """
        seen: dict[str, CircuitReading] = {}
        while True:
            readings = await self.read_all()
            for r in readings:
                prev = seen.get(r.dsuid)
                if prev is None:
                    seen[r.dsuid] = r
                    continue
                if prev.state is not r.state:
                    seen[r.dsuid] = r
                    yield prev, r
                else:
                    seen[r.dsuid] = r
            await asyncio.sleep(self._poll_interval)

    async def _read_one_circuit(self, circuit: Circuit) -> CircuitReading:
        raw_props: dict[str, Any] = {}
        consumption_api_failed = False

        # Parallel-read all property tree fields
        async def _read_field(name: str, getter: str) -> tuple[str, Any]:
            try:
                result = await self._client.get(
                    f"/json/property/{getter}",
                    params={"path": f"/apartment/dSMeters/{circuit.dsuid}/{name}"},
                )
                if isinstance(result, dict):
                    return name, result.get("value")
            except DssError:
                pass
            return name, None

        tasks = [_read_field(name, getter) for name, getter, _ in _READ_FIELDS]
        results = await asyncio.gather(*tasks)
        for name, value in results:
            raw_props[name] = value

        # Check whether circuit/getConsumption works (used to detect virtual circuits).
        # Use circuit.dsid (already the short form from getCircuits).
        short_dsid = circuit.dsid or short_dsid_from_dsuid(circuit.dsuid)
        try:
            await self._client.get(
                "/json/circuit/getConsumption",
                params={"id": short_dsid},
            )
        except DssError:
            consumption_api_failed = True

        raw_state = _to_int_safe(raw_props.get("state"))
        raw_present = _to_bool_safe(raw_props.get("present"))
        raw_is_valid = _to_bool_safe(raw_props.get("isValid"))
        raw_authorized = _to_bool_safe(raw_props.get("authorized"))
        raw_is_initialized = _to_bool_safe(raw_props.get("isInitialized"))

        state = classify_state(
            raw_state=raw_state,
            raw_present=raw_present,
            raw_is_valid=raw_is_valid,
            consumption_api_failed=consumption_api_failed,
        )

        watts = _to_int_safe(raw_props.get("powerConsumption"))
        # Treat 0 with present=False as None (no real reading)
        if state is CircuitState.OFFLINE and watts == 0:
            watts = None

        return CircuitReading(
            dsuid=circuit.dsuid,
            dsid=circuit.dsid or short_dsid_from_dsuid(circuit.dsuid),
            name=circuit.name,
            state=state,
            watts=watts,
            energy_wh=_to_float_safe(raw_props.get("energyMeterValue")),
            power_last_seen=_parse_dss_timestamp(raw_props.get("powerConsumptionAge")),
            energy_last_seen=_parse_dss_timestamp(raw_props.get("energyMeterAge")),
            raw_state=raw_state,
            raw_is_valid=raw_is_valid,
            raw_present=raw_present,
            raw_authorized=raw_authorized,
            raw_is_initialized=raw_is_initialized,
            timestamp=datetime.now(),
        )


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _to_int_safe(v: Any) -> int | None:
    if v is None:
        return None
    try:
        return int(v)
    except (ValueError, TypeError):
        return None


def _to_float_safe(v: Any) -> float | None:
    if v is None:
        return None
    try:
        return float(v)
    except (ValueError, TypeError):
        return None


def _to_bool_safe(v: Any) -> bool | None:
    if v is None:
        return None
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return bool(v)
    if isinstance(v, str):
        return v.strip().lower() in ("true", "1", "yes")
    return None


def _parse_dss_timestamp(v: Any) -> datetime | None:
    """Parse the dSS server-local timestamp format ``YYYY-MM-DD HH:MM:SS``.

    Returns a naive datetime (no tzinfo) to match the dSS server's local
    clock. Library users comparing against ``datetime.now()`` (also naive
    local) will get sensible age values as long as the dSS and the host
    run in the same timezone - which is the common case.

    Returns None for missing values or epoch markers (``1970-01-01...``).
    """
    if v is None:
        return None
    s = str(v).strip()
    if not s or s.startswith("1970-01-01"):
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S"):
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue
    return None
